data:
  path: /kaggle/input/entrep-dataset/Dataset
  json_path: splits_info.json
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  image_size: 224
  normalize: true

model:
  vision_encoder:
    type: dinov2
    feature_dim: 768
    model_name: dinov2_vits14
    ckp_path: /kaggle/input/ent-pretrained/Pretrained/dinov2_vits14.pth
  text_encoder:
    type: clip
    feature_dim: 768
    model_name: openai/clip-vit-base-patch32
  temperature: 0.07

trainer:
  num_epochs: 50
  batch_size: 32
  learning_rate: 0.00001
  weight_decay: 0.05
  output_path: /kaggle/working/checkpoints/dinos_clip
  model_name: dinos
