data:
  path: Dataset/
  json_path: splits_info.json
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  image_size: 224
  normalize: true

model:
  vision_encoder:
    type: endovit
    feature_dim: 768
    model_name: egeozsoy/EndoViT
    ckp_path: Pretrained/ent_vit/best_model.pth
  text_encoder:
    type: clip
    feature_dim: 768
    model_name: openai/clip-vit-base-patch32
  temperature: 0.07

trainer:
  num_epochs: 10
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  output_path: checkpoints/
  model_name: endovit
