data:
  path: Dataset/
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  image_size: 224
  normalize: true

model:
  vision_encoder:
    type: dino
    feature_dim: 768
    model_name: facebook/dinov2_vitb14
  text_encoder:
    type: clip
    feature_dim: 768
    model_name: openai/clip-vit-base-patch32
  temperature: 0.07

trainer:
  num_epochs: 10
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  device: cuda